# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f40295cfd77fdab53296bf1af32e933de4bdd52a27bffad64c8bf06ad2af8541be65ea3bc215df47bd4d26e20dd51d4d70f9229de8a13c0268dba0aedee3d8ab

test:
  secret_key_base: 19c5cd01667ba4a8cb381986791fe314be697f06ec9813bf31e34a28b27dcc60c41601ec673e554bdca41676cf236ad5ebff1d3e784fabe659dad384fa8f755d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
